# Generated by Django 2.2.7 on 2019-11-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richfieldVSP', '0002_auto_20191106_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email_address', models.TextField()),
                ('contact_number', models.TextField()),
                ('gender', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('course', models.TextField()),
                ('current_year', models.TextField()),
            ],
        ),
    ]
